//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSE445Homework3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/create_calendar", ReplyAction="http://tempuri.org/IService1/create_calendarResponse")]
        string create_calendar(int startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/create_calendar", ReplyAction="http://tempuri.org/IService1/create_calendarResponse")]
        System.Threading.Tasks.Task<string> create_calendarAsync(int startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEvent", ReplyAction="http://tempuri.org/IService1/AddEventResponse")]
        string AddEvent(string calendar, int day, string name, string description, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEvent", ReplyAction="http://tempuri.org/IService1/AddEventResponse")]
        System.Threading.Tasks.Task<string> AddEventAsync(string calendar, int day, string name, string description, string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalendarToDisplay", ReplyAction="http://tempuri.org/IService1/CalendarToDisplayResponse")]
        string CalendarToDisplay(string cal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalendarToDisplay", ReplyAction="http://tempuri.org/IService1/CalendarToDisplayResponse")]
        System.Threading.Tasks.Task<string> CalendarToDisplayAsync(string cal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CSE445Homework3.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CSE445Homework3.ServiceReference1.IService1>, CSE445Homework3.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string create_calendar(int startDate) {
            return base.Channel.create_calendar(startDate);
        }
        
        public System.Threading.Tasks.Task<string> create_calendarAsync(int startDate) {
            return base.Channel.create_calendarAsync(startDate);
        }
        
        public string AddEvent(string calendar, int day, string name, string description, string start, string end) {
            return base.Channel.AddEvent(calendar, day, name, description, start, end);
        }
        
        public System.Threading.Tasks.Task<string> AddEventAsync(string calendar, int day, string name, string description, string start, string end) {
            return base.Channel.AddEventAsync(calendar, day, name, description, start, end);
        }
        
        public string CalendarToDisplay(string cal) {
            return base.Channel.CalendarToDisplay(cal);
        }
        
        public System.Threading.Tasks.Task<string> CalendarToDisplayAsync(string cal) {
            return base.Channel.CalendarToDisplayAsync(cal);
        }
    }
}
